### ISSUE TITLE
Cannot use ModelloCLI to convert .mdo files into *.java files - Unable to load java plugin

### ISSUE THREAD

**Issue by wltjr** [codehaus-plexus/modello#15]
I am doing abnormal things! I have modello built and running fine. I am trying to use the java plugin. I am seeing some really strange stuff. It seems to initialize twice, and only on the first is the plugins populated. Such that when it goes to getPlugin, the hashmap is empty. I added some debug code.

```patch
--- a/src/main/java/org/codehaus/modello/plugin/AbstractPluginManager.java
+++ b/src/main/java/org/codehaus/modello/plugin/AbstractPluginManager.java
@@ -42,6 +42,17 @@ public abstract class AbstractPluginManager<T>

     public void initialize()
     {
+        System.out.println("init");
+        printMap();
+    }
+
+    public void printMap()
+    {
+        for (String name: plugins.keySet()){
+            String key = name.toString();
+            String value = plugins.get(name).toString();
+            System.out.println(key + " " + value);
+        }
     }

     public Map<String, T> getPlugins()
@@ -56,6 +67,8 @@ public abstract class AbstractPluginManager<T>

     public T getPlugin( String name )
     {
+        printMap();
+        System.out.println("getPlugin = "+name);
         T plugin = plugins.get( name );

         if ( plugin == null )
```

Here is the output,and you can see the plugins are available at first. But then it inits again, not sure why. Seems that is where the empty hashmap comes from. Next I will throw an exception so I can see what is calling that each time. Not sure if this is a bug, or usability issues. Maybe order of plexus jars on classpath? I am doing this via command line, ModelloCLI.

You can see the 2 inits, and by the time it calls getPlugin method, its empty.
```java
init
model org.codehaus.modello.plugin.model.ModelMetadataPlugin@52d455b8
java org.codehaus.modello.plugin.java.metadata.JavaMetadataPlugin@6956de9
init
getPlugin = java
Exception in thread "main" org.codehaus.modello.ModelloRuntimeException: No such plugin: java
        at org.codehaus.modello.plugin.AbstractPluginManager.getPlugin(AbstractPluginManager.java:76)
        at org.codehaus.modello.core.DefaultGeneratorPluginManager.getGeneratorPlugin(DefaultGeneratorPluginManager.java:38)
        at org.codehaus.modello.core.DefaultModelloCore.generate(DefaultModelloCore.java:374)
        at org.codehaus.modello.Modello.generate(Modello.java:65)
        at org.codehaus.modello.ModelloCli.main(ModelloCli.java:49)
```

**Comment by wltjr** [comment]
Looks like this is a [long time known issue](https://github.com/codehaus-plexus/modello/blob/master/src/site/apt/release-notes.apt#L255) since 2009...

**Comment by wltjr** [comment]
That issue is unrelated, as it was from a missing jar/cnfe. I believe I am having a Generator issue. It seems to find and list the MetaDataPlugins _JavaMetaDataPlugin_, but not sure about the Generators, _JavaModelloGenerator_.

If I add the following to modello-core components.xml. Which I know is incorrect, but it is the only change that seems to have any effect. Also what makes me think my problem is something related to Generators, that plugin manager or something.
```diff
--- a/src/main/resources/META-INF/plexus/components.xml
+++ b/src/main/resources/META-INF/plexus/components.xml
@@ -41,5 +41,10 @@
       <role-hint>model</role-hint>
       <implementation>org.codehaus.modello.plugin.model.ModelMetadataPlugin</implementation>
     </component>
+    <component>
+      <role>org.codehaus.modello.plugin.ModelloGenerator</role>
+      <role-hint>model</role-hint>
+      <implementation>org.codehaus.modello.core.DefaultGeneratorPluginManager</implementation>
+    </component>
   </components>
 </component-set>
```

I get the following output. Without I do not get the lines with DefaultGeneratorPluginManager
```java
# modello extension.mdo java src/main/java 4.0.0 false true

DefaultPlexusContainer
AbstractPluginManager.initialize()
plugins = 2
model : org.codehaus.modello.plugin.model.ModelMetadataPlugin@2b4a2ec7
java : org.codehaus.modello.plugin.java.metadata.JavaMetadataPlugin@62e136d3
AbstractPluginManager.initialize()
plugins = 3
AbstractPluginManager.initialize()
plugins = 0
model : org.codehaus.modello.core.DefaultGeneratorPluginManager@2c34f934
ModelloCore
new Modello()
parsed args
generatorId =java
plugins = 3
model : org.codehaus.modello.core.DefaultGeneratorPluginManager@2c34f934
getPlugin = java
Exception in thread "main" org.codehaus.modello.ModelloRuntimeException: No such plugin: java
        at org.codehaus.modello.plugin.AbstractPluginManager.getPlugin(AbstractPluginManager.java:73)
        at org.codehaus.modello.core.DefaultGeneratorPluginManager.getGeneratorPlugin(DefaultGeneratorPluginManager.java:39)
        at org.codehaus.modello.core.DefaultModelloCore.generate(DefaultModelloCore.java:374)
        at org.codehaus.modello.Modello.generate(Modello.java:67)
        at org.codehaus.modello.ModelloCli.main(ModelloCli.java:51)
```


Then if I pass model as the argument instead of java.
```java
modello extension.mdo model src/main/java 1.0.0 false true

DefaultPlexusContainer
AbstractPluginManager.initialize()
plugins = 2
model : org.codehaus.modello.plugin.model.ModelMetadataPlugin@7fe8ea47
java : org.codehaus.modello.plugin.java.metadata.JavaMetadataPlugin@1dd92fe2
AbstractPluginManager.initialize()
plugins = 2
AbstractPluginManager.initialize()
plugins = 0
model : org.codehaus.modello.core.DefaultGeneratorPluginManager@176d53b2
ModelloCore
new Modello()
parsed args
generatorId =model
plugins = 2
model : org.codehaus.modello.core.DefaultGeneratorPluginManager@176d53b2
getPlugin = model
Exception in thread "main" java.lang.ClassCastException: org.codehaus.modello.core.DefaultGeneratorPluginManager cannot be cast to org.codehaus.modello.plugin.ModelloGenerator
        at org.codehaus.modello.core.DefaultGeneratorPluginManager.getGeneratorPlugin(DefaultGeneratorPluginManager.java:39)
        at org.codehaus.modello.core.DefaultModelloCore.generate(DefaultModelloCore.java:374)
        at org.codehaus.modello.Modello.generate(Modello.java:67)
        at org.codehaus.modello.ModelloCli.main(ModelloCli.java:51)
```

**Comment by fridrich** [comment]
Whenever I had this kind of problem, it was classpath problem. Currently the modello script in openSUSE, we generate it with this macro:

%jpackage_script org.codehaus.modello.ModelloCli "" "-Dguice_custom_class_loading=CHILD" modello:aopalliance:atinject:commons-lang3:google-guice:guava:jackson-core:jakarta-inject:javadoc-parser:jsoup/jsoup:objectweb-asm/asm:plexus/plexus-build-api:plexus/plexus-build-api0:plexus/classworlds:plexus-containers/plexus-component-annotations:plexus/utils:plexus/xml:org.eclipse.sisu.inject:org.eclipse.sisu.plexus:slf4j/api:slf4j/simple:snakeyaml:velocity-engine/velocity-engine-core %{name} true

where modello on classpath means all the jars in /usr/share/java/modello directory. Jakarta-inject is there because our version of guice is the one that supports both javax.inject (imported as atinject) and jakarta.inject (imported as jakarta-inject). plexus-xml because we use plexus-utils 4.x with plexus-xml 3.x. This is the classpath that works fine and is able to generate - using command-line tool - the files needed for maven 3.x build. Also for maven 4, but with additional patches to support velocity stuff.

**Comment by fridrich** [comment]
Normally, now after the migration to sisu inject, and these options of the DefaultContainerConfiguration:                   setClassPathScanning(PlexusConstants.SCANNING_INDEX) and setAutoWiring(true), the different plugins should be found if on the classpath. At least for me the two options were critical after the migration and I remember we were fine-tuning it with Tamas back then. The plugins have all the javax.inject.Named generated and that should be enough to instantiate them provided sisu-plexus is on the classpath and not the old plexus-container-default that does not know how to lookup the jsr330 components.

I would lean towards closing this one. I am using the command-line tool for years and it just works for me.

**Comment by fridrich** [comment]
The fact is that modello-core where the cli tool resides does not require any of the plugins, so automagically they will not be taken. They have to be put on the classpath on purpose. I cannot reproduce that error :( and I tried several times, but I remember that I saw it some years ago, many years ago at the height of 1.x but don't remember :( anything more detailed.
