### ISSUE TITLE
NoSuchMethodError when we combine Modello and Plexus 4 in a Maven plugin

### ISSUE THREAD

**Issue by alitokmen** [codehaus-plexus/modello#407]
Dear Modello team

As we upgraded to Plexus 4, dark issues started to appear - Namely, the below exception in the code that Modello itself generates:

```
java.lang.NoSuchMethodError: 'void org.codehaus.plexus.util.xml.Xpp3Dom.<init>(org.apache.maven.api.xml.XmlNode)'
        at org.codehaus.plexus.util.xml.Xpp3DomBuilder.build(Xpp3DomBuilder.java:85)
        at org.codehaus.plexus.util.xml.Xpp3DomBuilder.build(Xpp3DomBuilder.java:76)
        at org.codehaus.cargo.maven3.io.xpp3.UberWarXpp3Reader.parseMerge(UberWarXpp3Reader.java:712)
        at org.codehaus.cargo.maven3.io.xpp3.UberWarXpp3Reader.parseMergeRoot(UberWarXpp3Reader.java:781)
        at org.codehaus.cargo.maven3.io.xpp3.UberWarXpp3Reader.read(UberWarXpp3Reader.java:582)
        at org.codehaus.cargo.maven3.io.xpp3.UberWarXpp3Reader.read(UberWarXpp3Reader.java:613)
        at org.codehaus.cargo.maven3.io.xpp3.UberWarXpp3Reader.read(UberWarXpp3Reader.java:628)
        at org.codehaus.cargo.maven3.UberWarMojo.execute(UberWarMojo.java:201)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        ... 12 common frames omitted
```

The relevant sources:
* Build XML with the Modello references: https://github.com/codehaus-cargo/cargo/blob/master/extensions/maven3/plugin/pom.xml
* MDO file: https://github.com/codehaus-cargo/cargo/blob/master/extensions/maven3/plugin/src/main/mdo/mergeinfo.mdo
* Maven project to reproduce: https://github.com/RussiaVk/uberwar-reproduce

Workaround: In the Maven 3 plugin we use,
* Remove dependency from Plexus utils 4.0.0 and Plexus XML 4.0.3
* Use instead dependency to Plexus utils 3.5.1

How can we fix these?

**Comment by alitokmen** [comment]
More specifically, we found that the parsing of the `<merges>` seem to be causing the issue:
* Modello's parsing of https://github.com/codehaus-cargo/cargo/blob/master/extensions/maven3/samples/uberwar-test/src/test/resources/merge.xml works fine
* Mpdello's parsing of https://github.com/RussiaVk/uberwar-reproduce/blob/main/deploy/src/main/resources/merge.xml fails as described above

The `<merges>` element is defined in https://github.com/codehaus-cargo/cargo/blob/master/extensions/maven3/plugin/src/main/mdo/mergeinfo.mdo

**Comment by alitokmen** [comment]
Hi everyone

It turns out, this is not Modello related - And rather an awkward clash between the Plexus versions, changing class signatures and how Maven brings them together:
* Between versions 3.x and 4.x, there were quite some changes in the Plexus XML libraries
* Maven 3.x is shipped with Plexus 3.x, directly in its `MAVEN_HOME/lib` folder
* Last but not least, Plexus' XML libraries seem to be "sticky", hence the signatures of Java classes from the Plexus 3.x versions end up finding their way to other classloaders

As a workaround, on the Codehaus Cargo side, we now implemented https://github.com/codehaus-cargo/cargo/commit/842436544c75477a90e1d1a2a2cdd4af85b1ac35 - Which is very ugly (but works):
1. It first tries to load the Modello-based reader "normally" (though we use reflection so we can catch exceptions)
2. When that fails with `ClassNotFoundException` or `NoClassDefFoundError`, it navigates in the `ClassLoader` mechanisms, but also in the `MAVEN_HOME/lib` folder, to identify the "rootmost" version of Plexus Utils that's somewhere in the JVM. It then forces that same version to be injected into the plugin's `ClassRealm`.

This is definitely very, very ugly - And would potentially cause other dark issues. Nevertheless, the only alternative I could think of is the manual workaround of asking the user to add thePlexus Utils 3.x in the plugin configuration.

Sorry for the intermediate noise.

Regards
